### ISSUE TITLE
Warning: unclosed client session

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/itsybitsy#2]
I am getting an unclosed client session warning:

```
c:\...\site-packages\itsybitsy\spider\asynchronous.py:149: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session.close()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AEFAE10C50>
```

I can see this issue also is discussed here: https://stackoverflow.com/questions/46112848/python-package-aiohttp-has-a-warning-message-unclosed-client-session

I also have the problem that the server kicks me out due to too many requests - I do not know whether closing the sessions could solve that? In any case, I guess we better close them.

**Comment by mrpgraae** [comment]
How / from where is `itsybitsy.crawl` called?

**Comment by j08lue** [comment]
https://github.com/DHI-GRAS/vito-download/blob/f7823d8cdf19d1768e8be92f0587b1b082c860fd/vito_download/download.py#L82

**Comment by dionhaefner** [comment]
The warning should give you the missing clue (should be `await session.close()`)

**Comment by j08lue** [comment]
It *is* `await session.close()` in the line which the warning references: 

https://github.com/DHI-GRAS/itsybitsy/blob/81eca61a571d0791a8a18d7f4a19585012eedf86/itsybitsy/spider/asynchronous.py#L149

**Comment by dionhaefner** [comment]
Not in the error message?

**Comment by j08lue** [comment]
You are right. I just did not have the newest code. Guess we should make a new release. But I can also see that this is nothing more than a warning then.
